// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ84NdxPNRTbEQeKMGDLqNBfjbRLzzeq0',
    appId: '1:1066724452466:web:fd9ad005c9418e6701baeb',
    messagingSenderId: '1066724452466',
    projectId: 'chat-app1-ba67f',
    authDomain: 'chat-app1-ba67f.firebaseapp.com',
    storageBucket: 'chat-app1-ba67f.appspot.com',
    measurementId: 'G-L597FXV3R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRl6SxjVadOf136V2K0-Buyw-T9uvE4to',
    appId: '1:1066724452466:android:de34b9c573b3d22401baeb',
    messagingSenderId: '1066724452466',
    projectId: 'chat-app1-ba67f',
    storageBucket: 'chat-app1-ba67f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCckYsR3MKweSk5RJwnLhsnpYfxgbearis',
    appId: '1:1066724452466:ios:bd5b5df49095684d01baeb',
    messagingSenderId: '1066724452466',
    projectId: 'chat-app1-ba67f',
    storageBucket: 'chat-app1-ba67f.appspot.com',
    iosBundleId: 'com.example.chat1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCckYsR3MKweSk5RJwnLhsnpYfxgbearis',
    appId: '1:1066724452466:ios:7a2f6e4517aafec001baeb',
    messagingSenderId: '1066724452466',
    projectId: 'chat-app1-ba67f',
    storageBucket: 'chat-app1-ba67f.appspot.com',
    iosBundleId: 'com.example.chat1.RunnerTests',
  );
}
